---

- name: install and configure spark
  hosts: frontendnodes
  become: yes
  roles:
    - role: java
    - role: maven
    - role: spark
      spark_version: 1.6.0
      spark_package_type: bin
      spark_internal_iface: "{{ bds_internal_iface }}"
